package it.univaq.disim.ing.univasa.domain;

public enum TipologiaMedico {
	PEDIATRA, PSICHIATRA, CHIRURGO, GINECOLOGO, OCULISTA, MEDICODIBASE, DENTISTA, OTORINO, DIETELOGO, NEUROLOGO,
	ALLERGOLOGO, CARDIOLOGO
}
