package it.univaq.disim.oop.pharma.domain;

public enum TipologiaMedico {
	PEDIATRA, PSICHIATRA, CHIRURGO, GINECOLOGO, OCULISTA, MEDICODIBASE, DENTISTA, OTORINO, DIETELOGO, NEUROLOGO,
	ALLERGOLOGO, CARDIOLOGO
}
