-- MySQL Script generated by MySQL Workbench
-- Fri Jan 29 19:27:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema univasa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `univasa` ;

-- -----------------------------------------------------
-- Schema univasa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `univasa` DEFAULT CHARACTER SET utf8 ;
USE `univasa` ;

-- -----------------------------------------------------
-- Table `univasa`.`utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `univasa`.`utente` ;

CREATE TABLE IF NOT EXISTS `univasa`.`utente` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,1
  `nome` VARCHAR(50) NOT NULL,2
  `cognome` VARCHAR(50) NOT NULL,3
  `email` VARCHAR(50) NOT NULL,4
  `username` VARCHAR(50) NOT NULL,5
  `password` VARCHAR(50) NOT NULL,6
  `telefono` VARCHAR(11) NOT NULL,7
  `data_nascita` DATE NOT NULL,8
  `professione` ENUM('studente', 'professore', 'impiegato') NOT NULL,9
  `nome_universita` VARCHAR(50) NOT NULL,10
  `dipartimento` VARCHAR(50) NOT NULL,11
  `matricola` VARCHAR(10) NULL,12
  `tipo_utente` VARCHAR(15) NOT NULL,13
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univasa`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `univasa`.`evento` ;

CREATE TABLE IF NOT EXISTS `univasa`.`evento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `regolamento` TEXT(500) NOT NULL,
  `data_inizio` DATE NOT NULL,
  `data_fine` DATE NOT NULL,
  `ora_inizio` VARCHAR(8) NOT NULL,
  `ora_fine` VARCHAR(8) NOT NULL,
  `luogo` VARCHAR(50) NOT NULL,
  `report_risultati` TEXT(200) NULL,
  `report_statistiche` TEXT(200) NULL,
  `numero_preferenze_esprimibili` INT UNSIGNED NOT NULL,
  `stato` ENUM('programmato', 'in corso', 'terminato') NOT NULL DEFAULT 'programmato',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univasa`.`turnazione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `univasa`.`turnazione` ;

CREATE TABLE IF NOT EXISTS `univasa`.`turnazione` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_utente` INT UNSIGNED NOT NULL,
  `id_evento` INT UNSIGNED NOT NULL,
  `fascia` ENUM('mattina', 'pomeriggio', 'sera') NOT NULL,
  `data_giorno` DATE NOT NULL,
  INDEX `fk_utente_has_evento_evento1_idx` (`id_evento` ASC) VISIBLE,
  INDEX `fk_utente_has_evento_utente_idx` (`id_utente` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_utente_has_evento_utente`
    FOREIGN KEY (`id_utente`)
    REFERENCES `univasa`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_evento_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `univasa`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univasa`.`candidatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `univasa`.`candidatura` ;

CREATE TABLE IF NOT EXISTS `univasa`.`candidatura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_utente` INT UNSIGNED NOT NULL,
  `id_evento` INT UNSIGNED NOT NULL,
  `voti_ricevuti` INT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_utente_has_evento_evento2_idx` (`id_evento` ASC) VISIBLE,
  INDEX `fk_utente_has_evento_utente1_idx` (`id_utente` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_utente_has_evento_utente1`
    FOREIGN KEY (`id_utente`)
    REFERENCES `univasa`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_evento_evento2`
    FOREIGN KEY (`id_evento`)
    REFERENCES `univasa`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `univasa`.`prenotazione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `univasa`.`prenotazione` ;

CREATE TABLE IF NOT EXISTS `univasa`.`prenotazione` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_utente` INT UNSIGNED NOT NULL,
  `id_evento` INT UNSIGNED NOT NULL,
  `tipo_prenotazione` ENUM('online', 'in presenza') NULL,
  `stato` ENUM('si', 'no') NOT NULL DEFAULT 'no',
  `certificato` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utente_has_evento_evento3_idx` (`id_evento` ASC) VISIBLE,
  INDEX `fk_utente_has_evento_utente2_idx` (`id_utente` ASC) VISIBLE,
  CONSTRAINT `fk_utente_has_evento_utente2`
    FOREIGN KEY (`id_utente`)
    REFERENCES `univasa`.`utente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utente_has_evento_evento3`
    FOREIGN KEY (`id_evento`)
    REFERENCES `univasa`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
